{% set name = "tensorflow-metadata" %}
{% set version = "1.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: 2ce72ea31d78a00c0c74c6d465482335aa5cb2a3b2a104dedba0b258bc7bb18a

build:
  number: 0
  noarch: python


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - googleapis-common-protos >=1.56.4,<2
    - protobuf >=4.25.2,<5
    - absl-py >=0.9,<3.0.0
    - python >=3.7
test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
