{% set name = "tensorflow-metadata" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: 5ff79bf96f98c800fc08270b852663afe7e74d7e1f92b50ba1487bfc63894cdb

build:
  number: 0
  noarch: python


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - googleapis-common-protos >=1.52.0,<2
    - protobuf >=3.13
    - absl-py >=0.9,<2.0.0
    - python >=3.7
test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
