{% set name = "tensorflow-metadata" %}
{% set version = "1.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/metadata/archive/v{{ version }}.tar.gz
  sha256: a1ec0e258afb7515223a2d948e05a246e085888a91cce1a26106164871c28f00

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - absl-py >=0.9,<3.0.0 
    - googleapis-common-protos >=1.56.4,<2  # [py>=311]
    - googleapis-common-protos >=1.52.0,<2  # [py<311]
    - protobuf >=4.25.2,<6  # [py>=311]
    - protobuf >=3.20.3,<4.21  # [py<311]

test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tensorflow/metadata
  summary: Utilities for passing TensorFlow-related metadata between tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
    - ehfd
